#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling,linting and building your project before committing'

# Format to Check Prettier standards
npm run format

npm run lint ||
(
        echo '😤🏀👋😤 Get that weak shit out of here! 😤🏀👋😤
                ESLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false;
)

# Check tsconfig standards
npm run check-types ||
(
    echo '🤡😂❌🤡 Failed Type check. 🤡😂❌🤡
            Are you seriously trying to write that? Make the changes required above.

            '
    false;
)

# If everything passes... Now we can commit
echo '
       ✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅

       '
